---
- name: firewall config
  hosts: gateway

  tasks:
    - name: enable and start firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes
      become: yes

    - name: configure firewalld
      shell: |
        firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -o tun0 -j MASQUERADE
        firewall-cmd --direct --add-rule ipv4 filter FORWARD 0 -i eth1 -o tun0 -j ACCEPT
        firewall-cmd --direct --add-rule ipv4 filter FORWARD 0 -i tun0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
        firewall-cmd --runtime-to-permanent
        firewall-cmd --direct --get-all-rules
      become: yes
      register: firewall_cmd_result

    - name: firewalld output
      debug: var=firewall_cmd_result.stdout_lines
