#
# (c) Copyright 2018 Jeff Kight
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Ansible playbook for F5 gateway automation
#
# Author: Jeff Kight <jeff@kight.net>
#
---
- name: vpn install
  hosts: gateway

  tasks:
    - name: create F5 directory
      file:
        path: "{{ ansible_user_dir }}/f5"
        state: directory
        mode: 0755

    - name: extract F5 client
      unarchive:
        src: linux_sslvpn.tgz
        dest: "{{ ansible_user_dir }}/f5"

    - name: install F5 client
      shell: echo "yes" | ./Install.sh
      args:
        chdir: "{{ ansible_user_dir }}/f5"
        creates: /usr/local/bin/f5fpc
      become: yes

    - name: create F5 client wrapper
      shell: echo "f5fpc --start --host {{ F5_host }} --user {{ F5_user }} --password '{{ F5_pass }}' --nocheck" > /usr/local/bin/vpnup
      args:
        creates: /usr/local/bin/vpnup
      become: yes
      no_log: true

    - name: set permissions on wrapper
      file:
        path: /usr/local/bin/vpnup
        mode: 0755
      become: yes
